### ISSUE TITLE
Could I Help

### ISSUE THREAD

**Issue by uselesswaifu** [ReduxRedstone/MCPE-Citizens#1]
Could i be of some help of your Project, I would love to see this succeed

**Comment by ReduxRedstone** [comment]
This repo and version of the plugin is no longer maintained as working with raw packets made it difficult to control certain aspects of the NPC, such as the skin. I have opened a new repo under the name Citizens2 and will maintain that repo and version of the plugin instead.
[https://github.com/ReduxRedstone/MCPE-Citizens2](https://github.com/ReduxRedstone/MCPE-Citizens2)

**Comment by uselesswaifu** [comment]
@ReduxRedstone Using real Entities will run into more Issues I suggest Looking at the [This](https://github.com/onebone/NPC) For Help with Maintaining Packets

**Comment by ReduxRedstone** [comment]
Using real entities has worked just fine for me. Everything is working as it should and I have much better control over the actual NPC. It is even a common suggestion on the PMMP forums to change from packets to entities. If you would like to fork this repo, which uses packets, and maintain it then please do. But I will no longer be supporting the packet-based version.
